source("D:/Allan/DropBox/RWorkingDir/Trading/Dax/addTA_fnc.R")
setwd("D:/Allan/DropBox/RWorkingDir/Trading/Dax")
Mkt <- read.csv("D:/Allan/DropBox/RWorkingDir/Trading/Data/Dax_ta.csv")
ln <- nrow(Mkt) 
lw <- 300
Mkt <- Mkt[3430:ln,]
head(Mkt)
nrow(Mkt)

tail(b[,c(1,10,13,14,16,17)],n=30)

c('run',' 2')
b <- calcT2(Mkt,2)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])

c('run',' 3')
b <- calcT2(Mkt,3)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])

c('run',' 4')
b <- calcT2(Mkt,4)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])


c('run',' 6')
b <- calcT2(Mkt,6)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])

c('run',' 7')
b <- calcT2(Mkt,7)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])

c('run',' 8')
b <- calcT2(Mkt,8)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])

c('run',' 9')
b <- calcT2(Mkt,9)
sum(b$PL2, na.rm=T)
sum(b$PL2>0, na.rm=T) / (sum(b$PL2>0, na.rm=T) + sum(b$PL2<0, na.rm=T))
bb <- na.omit(b) 
mean(bb[bb$PL2>0,18])
mean(bb[bb$PL2<0,18])