Magic
========================================================

```{r echo=FALSE}
#setwd("F:/Allan/R Stuff/Dax")
setwd("D:/Allan/DropBox/RWorkingDir/Trading/Dax")

library(xtable)
library(TTR)
library(candlesticks)

```

```{r echo=FALSE}
# Add TA info to just one indice
addTAInd <- function(Mkt){
  #browser()
  Mkt[2:5] <- round(Mkt[2:5])
  #atr
  
  atr <- ATR(Mkt[,c("High","Low","Close")], n=14)
  Mkt$atr <- round(atr[,"atr"])
  
  #SMA
  sma <- round(SMA(Mkt["Close"], 10))
  Mkt <- cbind(Mkt, sma)
  Mkt$Diff <- ifelse(!is.na(Mkt$sma), Mkt$Close - Mkt$sma, NA)
  
  #aroon
  ar <- aroon(Mkt$Close, n=20)
  Mkt <- cbind(Mkt, ar)
  #roc
  Mkt$mom <- round(momentum(Mkt$Close,n=12)) 
  lw <- quantile(Mkt$mom, na.rm=T, probs=0.25) 
  hi <- quantile(Mkt$mom, na.rm=T, probs=0.75)
  Mkt$hi <- round(hi)
  Mkt$lw <- round(lw)
  
  #Candlesticks
  Mkt_xts <- xts(Mkt[,c(2,3,4,5)],Mkt$Date)
  #browser()
  hh <- as.data.frame(CSPHammer(Mkt_xts))
  hi <- as.data.frame(CSPInvertedHammer(Mkt_xts))
  en <- as.data.frame(CSPEngulfing(Mkt_xts))
  dj <- as.data.frame(CSPDoji(Mkt_xts))
  #back to data fram
  Mkt <- cbind(Mkt,hh)
  Mkt <- cbind(Mkt,hi)
  Mkt <- cbind(Mkt,dj)
  Mkt <- cbind(Mkt,en)
  
  Mkt$pl <- Mkt$Close - Mkt$Open
  
  #browser()
  #write.csv(Mkt,nm,row.names=FALSE)
  #write.csv(Mkt,paste('../Data/', nm, sep=""),row.names=FALSE)
  return(Mkt)
}

```


```{r echo=FALSE}

# three comparison functions
au_df2 <- function(Mkt, au, df){
  sum ( Mkt[ (Mkt$aroonUp == au) & 
               (Mkt$Diff > (df - 10) & Mkt$Diff < (df + 10)), 
             c(22) ] ,na.rm=T)
}

ad_df2 <- function(Mkt, ad, df){
  sum ( Mkt[ (Mkt$aroonDn == ad) & 
               (Mkt$Diff > (df - 10) & Mkt$Diff < (df + 10)), 
             c(22) ] ,na.rm=T)
}

os_df2 <- function(Mkt, os, df){
  sum ( Mkt[ (Mkt$oscillator == os) & 
               (Mkt$Diff > (df - 10) & Mkt$Diff < (df + 10)), 
             c(22) ] ,na.rm=T)
}

# # applies comp functions to one row, uisng current rows
r_p_ind <- function(Mkt, nr){
  browser()
  #Mkt <- AddPrev(Mkt)
  au <- Mkt$aroonUp[nr] 
  ad <- Mkt$aroonDn[nr] 
  os <- Mkt$oscillator[nr] 
  df <- Mkt$Diff[nr] 
  b <- au_df2(Mkt,au,df)
  d <- ad_df2(Mkt,ad,df)
  e <- os_df2(Mkt,os,df)
  e2 <- b+d+e
  return(c(b,d,e,e2))
}

# loops thru r_p - pass in how many times ...
run_rp_ind <- function(Mkt,ln){
  #browser()
  #Mkt <- AddPrev(Mkt)
  a <- c(0,0,0,0)
  for(i in 31:ln){
    b <- r_p_ind(Mkt,i)
    a <- rbind(a,b)
  }
  a <- a[-c(1),]
  return(a)
}

calcT <- function(Mkt){
ln <- nrow(Mkt) ;ln
dd <- run_rp_ind(Mkt,ln)
tail(dd)
colnames(dd) <- c('au_df','ad_df','os_df','tot')
dd2 <- as.data.frame(dd)
tail(dd2)  
Mkt <- cbind(Mkt[-c(1:30), ], dd2)
Mkt <- Mkt[ , c(1,2,3,4,5,6,22,23,24,25,26)]
Mkt$PL1 <- ifelse(Mkt$tot>0,Mkt$Close-Mkt$Open,Mkt$Open-Mkt$Close)
Mkt$WL <- ifelse(Mkt$PL1>0,1,0)
sm <- SMA(Mkt$WL, 10)*10
Mkt <- cbind(Mkt, sm)
sma <- SMA(Mkt$sm, 10)
Mkt <- cbind(Mkt, sma)
#add prev sm and sma
Mkt$prev_sm <- c( NA, Mkt$sm[ - length(Mkt$sm) ] )
Mkt$prev_sma <- c( NA, Mkt$sma[ - length(Mkt$sma) ] )
# cond for pl
Mkt$PL2 <- ifelse(Mkt$prev_sm>Mkt$prev_sma,Mkt$PL1,0)
  return(Mkt)
}

calcTgt5 <- function(Mkt){
  ln <- nrow(Mkt) ;ln
  dd <- run_rp(Mkt,ln)
  colnames(dd) <- c('au_df','ad_df','os_df','tot','pl2')
  dd2 <- as.data.frame(dd)
  Mkt <- cbind(Mkt[-c(1:30), ], dd2)
  Mkt <- Mkt[ , c(1,2,3,4,5,6,22,23,24,25,26)]
  Mkt$PL <- ifelse(Mkt$tot>0,Mkt$Close-Mkt$Open,Mkt$Open-Mkt$Close)
  Mkt$WL <- ifelse(Mkt$PL>0,1,0)
  sm <- SMA(Mkt$WL, 10)*10
  Mkt <- cbind(Mkt, sm)
  sm2 <- SMA(Mkt$sm, 10)
  Mkt <- cbind(Mkt, sm2)
  Mkt$PL2 <- ifelse(Mkt$sm>5,Mkt$PL,0)
  return(Mkt)
}

```

### Dax
```{r echo=FALSE}
# Add TA
#Mkt <- read.csv("F:/Allan/R Stuff/Dax/Dax_2000.csv")
#Mkt$Date <- as.POSIXct(Mkt$Date,format='%Y-%m-%d') ;Mkt$Date[20]
#Mkt$Date <- as.POSIXct(Mkt$Date,format='%d/%m/%Y') ;Mkt$Date[20]
#Mkt <- addTAInd(Mkt)
#write.csv(Mkt,"Dax_ta.csv",row.names=FALSE)

#Calc system
#Mkt <- read.csv("F:/Allan/R Stuff/Dax/Dax_ta.csv")
Mkt <- read.csv("D:/Allan/DropBox/RWorkingDir/Trading/Data/Dax_ta.csv")
#Add Prev Values
#Add pl col
colnames(Mkt)
length(Mkt)
Mkt$pl <- Mkt$Close - Mkt$Open

b <- calcT(Mkt)
a <- tail(b, n=15)

s <- sum(a$PL2, na.rm=T)
w <- sum(a$PL2>0, na.rm=T)
l <- sum(a$PL2<0, na.rm=T) 
lw <- round(w / (w+l),2) * 100

tail(Mkt)
r_p_ind(Mkt,3662)

nr <- 3662
au <- Mkt$aroonUp[nr] 
  ad <- Mkt$aroonDn[nr] 
  os <- Mkt$oscillator[nr] 
  df <- Mkt$Diff[nr]

sum ( Mkt[ (Mkt$aroonUp == au) & 
               (Mkt$Diff > (df - 10) & Mkt$Diff < (df + 10)), 
             c(22) ] ,na.rm=T)

```

Sum: `r s`, win rate: `r lw`

```{r echo=FALSE, results='asis'}
print(xtable(tail(a[c(1,2,3,4,5,11,12,13,14,15,16,17,18)])), type = "html")
```

